default_agent: BiblicalNewsAgent_CloudWatch
agents:
  BiblicalNewsAgent_CloudWatch:
    name: BiblicalNewsAgent_CloudWatch
    language: python
    node_version: '20'
    entrypoint: agent/agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_12
    platform: linux/arm64
    container_runtime: null
    source_path: .
    aws:
      execution_role: arn:aws:iam::923154133870:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1
      execution_role_auto_create: true
      account: '923154133870'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-923154133870-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: BiblicalNewsAgent_CloudWatch-b5yBJCH5Fu
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:923154133870:runtime/BiblicalNewsAgent_CloudWatch-b5yBJCH5Fu
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: BiblicalNewsAgent_CloudWatch_mem-Xb1N9sERy3
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:923154133870:memory/BiblicalNewsAgent_CloudWatch_mem-Xb1N9sERy3
      memory_name: BiblicalNewsAgent_CloudWatch_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
